### ISSUE TITLE
Remove (4K) from title

### ISSUE THREAD

**Issue by JoeDawson** [goto-bus-stop/get-artist-title#20]
Currently `Big Limit [@RealBigLimit] - Samurai Jack [Music Video] (4K)` is converted to `Big Limit – Samurai Jack  (4K)`

Can the `(4K)` and the additional whitespace be stripped too?

Thanks!

**Comment by goto-bus-stop** [comment]
seems useful, thanks! :package: 1.1.1

**Comment by JoeDawson** [comment]
Thanks so much!
